services:
  hugo:
    image: klakegg/hugo:0.101.0-ext-alpine
    command: server
    volumes:
      - "./src/:/src"
    ports:
      - 8080:1313

  cli:
    image: klakegg/hugo:0.101.0-ext-alpine
    entrypoint: /bin/sh -c 'while true; do sleep 86400; done'
    volumes:
      - "./src/:/src"

  hugo-production:
    build:
      context: .
      args:
        FROM_TAG: 0.101.0-ext-alpine-onbuild
    ports:
      - 8081:80